name = "finnh-ca"
compatibility_date = "2025-12-18"
assets = { directory = "./dist" }

[[routes]]
pattern = "finnh.ca"
custom_domain = true

[env.production.vars]
PUBLIC_COMMIT_HASH = "{{GIT_COMMIT_SHA}}"